Repository OpenMined/syft-proto, pull requests merged in 2020-06, with the labels that each got.

#127 Adding FixedPrecisionTensor support.
  js/protobuf.d.js
  js/protobuf.js
  jvm/src/main/java/org/openmined/syftproto/frameworks/torch/tensors/interpreters/v1/Precision.java
  protobuf/syft_proto/frameworks/torch/tensors/interpreters/v1/precision.proto
  swift/syft_proto/frameworks/torch/tensors/interpreters/v1/precision.pb.swift
  syft_proto/frameworks/torch/tensors/interpreters/v1/precision_pb2.py
Labels: Type: Improvement :chart_with_upwards_trend:

#125 Increasing size of arg int
  js/protobuf.d.js
  js/protobuf.js
  jvm/src/main/java/org/openmined/syftproto/types/syft/v1/ArgOuterClass.java
  protobuf/syft_proto/types/syft/v1/arg.proto
  swift/syft_proto/types/syft/v1/arg.pb.swift
  syft_proto/types/syft/v1/arg_pb2.py
Labels: Type: Bug :bug:

#118 Add child in Placeholder schema
  js/protobuf.d.js
  js/protobuf.js
  jvm/src/main/java/org/openmined/syftproto/execution/v1/PlaceholderOuterClass.java
  protobuf/syft_proto/execution/v1/placeholder.proto
  swift/syft_proto/execution/v1/placeholder.pb.swift
  syft_proto/execution/v1/placeholder_pb2.py
Labels: Type: New Feature :heavy_plus_sign:
